### ISSUE TITLE
Doesn't support Celery 4.0 (ie message protocol version 2)

### ISSUE THREAD

**Issue by pi-bjl** [lyst/celery-statsd#6]
Using this plugin with Celery 4.0.2 leads to exceptions such as the following:

```
2017-08-21 02:06:22,588 - celery.utils.dispatch.signal - ERROR - Signal handler <function statsd_after_task_publish at 0x7fe039437ed8> raised: TypeError('tuple indices must be integers, not str',)
Traceback (most recent call last):
  File "/var/lib/virtualenv/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 227, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/lib/virtualenv/lib/python2.7/site-packages/celery_statsd/__init__.py", line 87, in statsd_after_task_publish
    stop_timer("enqueue", task_key(sender), body['id'])
TypeError: tuple indices must be integers, not str
```
[Protocol version 2](http://docs.celeryproject.org/en/latest/internals/protocol.html) is the default from Celery 4.0. 3.1.25 offers both versions.

The difference here is that `id` will be in `headers` in version2, rather than `body`.

So both could be supported by doing something like  

```
    task_id = headers.get('id') or body.get('id')
```

**Comment by john-bodley** [comment]
@iserko @JeanFred @jesushernandez I was wondering whether you would consider reviewing @pi-bjl's change for adding support for Celery 4.0? I've run into the same issue and was thinking of authoring a similar solution. Note [here](http://docs.celeryproject.org/en/latest/userguide/signals.html#basics) is how the Celery documentation suggests one resolves the issue.
